### PR TITLE
Update cross browser support for getBrowserLang

### PR DESCRIPTION
**Pull request by jpinkster**
Right now the current method does not support the various browsers well based on the users defaults. This change will work across IE10+, safari, chrome, and firefox

### CODE REVIEW

**Comment by jpinkster** [comment]
Hey @ocombe, do you mind getting your eyes on this PR and let me know if it is something you will merge or not so that I can either use this helper method or move on? Thanks man.

**Comment by ocombe** [comment]
yes sorry, I will probably merge it, but I need to get my hands on a mac to test safari :)

**Comment by jpinkster** [comment]
Any luck testing this @ocombe

**Comment by ocombe** [comment]
Merged, thanks, and sorry for taking so long

**Pull request merged**
