### PR TITLE
Get multiple translations for a list of keys

### PR DESCRIPTION
**Pull request by NisStrom**

### CODE REVIEW

**Comment by ocombe** [comment]
Thanks, could you fix the errors ?

```sh
src/translate.service.ts(177,31): error TS7006: Parameter 'keys' implicitly has an 'any' type.

src/translate.service.ts(177,37): error TS7006: Parameter 'interpolateParams' implicitly has an 'any' type.

src/translate.service.ts(181,47): error TS7006: Parameter 'res' implicitly has an 'any' type.

src/translate.service.ts(185,7): error TS7017: Index signature of object type implicitly has an 'any' type.

src/translate.service.ts(194,17): error TS7017: Index signature of object type implicitly has an 'any' type.

src/translate.service.ts(197,20): error TS2304: Cannot find name 'Observable_1'.
```

**Comment by NisStrom** [comment]
Should be fixed now

**Comment by ocombe** [comment]
Almost, you need to change:
```js
public getAll = function (keys : Array<string>, interpolateParams?: Object) {
```

to
```js
public getAll(keys : Array<string>, interpolateParams?: Object) {
```

you can run `tsc` in your repository to see the typescript errors (or `npm run prepublish` if you don't have the typescript compiler installed globally).

**Comment by NisStrom** [comment]
It is OK now, do i need to close the pull request?

**Comment by ocombe** [comment]
Thanks, the tests work, don't close this I'll check it tonight and merge it then.

**Comment by ocombe** [comment]
Ok I changed this a bit, I didn't want to add a new method, so I added the option of the `get` method to use a single key or an array of keys.
It's available in v1.3.0

**Pull request closed without merging**
