### PR TITLE
feat(readme): added TOC and additional framework support section

### PR DESCRIPTION
**Pull request by NathanWalker**
This adds a Table of Contents for convenience and an 'Additional Framework Support' section since this library is now officially supported with `nativescript-angular` :+1: 

It could seemingly be bridged to work with other `native` or non-`native` frameworks so figured having a section would provide room to grow :)

### CODE REVIEW

**Comment by ocombe** [comment]
Nice, could you just change the commit message from "feat" to "docs" ? I don't want the merge to trigger a new release for that :P

**Comment by NathanWalker** [comment]
Good to know for future ;) There ya' go!

**Comment by ocombe** [comment]
Woops, should have renamed the merged before I did it. I canceled travis to make sure it doesn't release.

**Comment by NathanWalker** [comment]
Oh shoot. Ok yeah didn't know it triggered with PR names as well (was thinking only commits) ... 
#facepalm

Sry if that caused you any trouble!

**Pull request merged**
