### PR TITLE
Feature/implement merging

### PR DESCRIPTION
**Pull request by pfrendo**
Added merge option on setTranslations so one has the possibility of merging instead of overriding. Not a breaking change.

### CODE REVIEW

**Comment by pfrendo** [comment]
@ocombe any progress :)

**Comment by ocombe** [comment]
sorry, totally forgot about that, I'll try to check it this week

**Comment by pfrendo** [comment]
@ocombe thanks

**Comment by pfrendo** [comment]
@ocombe ping, would really like to help you improve this as I think it's a really good library but help me help you :+1:

**Comment by pfrendo** [comment]
@ocombe ping

**Comment by ocombe** [comment]
Sorry, my wife gave birth a month ago and I'm just starting to catch up with all my side projects :)

**Comment by ocombe** [comment]
Merged in 2.4

**Comment by Sergejack** [comment]
Can somebody provide an example how to achieve this?

**Comment by pfrendo** [comment]
@Sergejack all you do is set the `shouldMerge` flag to `true` when using the `setTranslation` method

**Comment by Dunos** [comment]
@pfrendo @ocombe does this mean that if I have a lazy loaded module with its own translation files (one for each language), I have to load those .json manually and then use the `setTranslation ` with that flag? In that case, should I have to manually load the specific .json file every time the user changes the language in the app? 

Maybe I'm missing something here or just mixing things on my head...

**Pull request closed without merging**
