### PR TITLE
Allow user to reload lang file

### PR DESCRIPTION
**Pull request by dy0nysos**

### CODE REVIEW

**Comment by ocombe** [comment]
Hello, thank you for the PR.
Could you also update the README.md file (required), and add some tests (not required) please?

**Comment by dy0nysos** [comment]
Hello @ocombe 
I updated the readme file.
Is anything else required for this pull requests to be merged ?

Thanks

**Comment by ocombe** [comment]
You added the method `reset` in the readme, but in the code it's `resetLang`. 
Also you don't document the method `reloadLang`.

Once that's done I'll merge it.

**Comment by dy0nysos** [comment]
My bad, wasn't attentive enough when I did this modification.
It should be ok now.

Also declared resetLang method public instead of private.

**Comment by ocombe** [comment]
Merged in https://github.com/ocombe/ng2-translate/commit/475a1a97

**Pull request closed without merging**
