### PR TITLE
fix(TranslateModule): use exported factory function to enable AOT compiling

### PR DESCRIPTION
**Pull request by frederikschubert**
I haven't tested it with this module but in other cases this change fixed the problem.

Should close https://github.com/ocombe/ng2-translate/issues/218

### CODE REVIEW

**Comment by ocombe** [comment]
Ah thanks, that's a weird solution, I'll take a look asap to know if it works

**Comment by frederikschubert** [comment]
Yes it is weird but others have found similar [problems/solutions](https://github.com/ngrx/store/pull/208#issuecomment-245598623) for the AOT compiler.

**Comment by BrainsoftLtd** [comment]
Please merge this, because other projects are running into the same problems (angular2-seed-advanced for one)...

**Comment by ocombe** [comment]
Yes sorry about that, I'll merge this as I don't see how it can do any harm anyway :)
Thanks for the PR @frederikschubert

**Comment by BrainsoftLtd** [comment]
Wow, that was fast :)

**Comment by ocombe** [comment]
You can try version 2.4.4 :-)

**Pull request merged**
