### PR TITLE
fix #53: dots in json keys is valid, but the parser doesn't acknowledge that

### LINKED ISSUE #53: useStaticFilesLoader is not a function ?
Hi all,

I have a problem when use `ng2-translate`
This is my code

`Boot.ts`
```
import {provide} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
import {ROUTER_PROVIDERS, LocationStrategy, HashLocationStrategy} from 'angular2/router';
import {HTTP_PROVIDERS, Http} from 'angular2/http';
import {TRANSLATE_PROVIDERS, TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';
import {Helper} from './utils/helper';
import {BaseHTTP} from './utils/baseHTTP';
import {App} from './app';

bootstrap(App, [
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS, 
    TRANSLATE_PROVIDERS,
    TranslateService,
    Helper,
    BaseHTTP,
    provide(LocationStrategy, { useClass: HashLocationStrategy })
]);
````

`app.ts`
```
import {Component, Injectable, provide} from 'angular2/core';
import {RouterOutlet, RouteConfig} from 'angular2/router';
import {Http} from 'angular2/http';
import {TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';

@Injectable()
@Component({
    selector: 'main-app',
    templateUrl: './src/app/app.html',
    directives: [RouterOutlet],
    pipes: [TranslatePipe]
})
export class App {
    public translate;

    constructor(translate: TranslateService) {
        this.translate = translate;

        this.translationConfig();
    } 
    
    translationConfig() {
        var prefix = 'src/app/core/languages';
        var suffix = '.json';
        var userLang = 'en';
        this.translate.useStaticFilesLoader(prefix, suffix);
        this.translate.use(userLang);
    }  
}
```
And an error occurs `this.translate.useStaticFilesLoader is not a function`. But it work in last friday (4/3/2016) and today it don't work.
Please help me, thanks

### PR DESCRIPTION
**Pull request by ribizli**

### CODE REVIEW

**Comment by ocombe** [comment]
Looks good, I'll check it more tonight & merge it

**Comment by Dinistro** [comment]
This will not work if there are keys like this:

```
'key' : 'value',
'key.subkey' : 'another value'
```

**Comment by ocombe** [comment]
Could you update your PR for that case @ribizli ?

**Comment by ribizli** [comment]
I think we need here some convention. We cannot cover all the cases. E.g.:
```js
{
	a: {
		b: {
			c: 'a/b/c'
		}
	},
	'a.b': {
		c: 'a.b/c'
	},
	'a.b.c': 'a.b.c'
}
```
Which one we return on `'a.b.c'`? (The current implementation does the first one)

Actually I like the current implementation, since it prefers the nested version against the dotted keys.

**Comment by ocombe** [comment]
I agree, mixing keys with dots & nesting doesn't make sense.

**Comment by ocombe** [comment]
Merged in https://github.com/ocombe/ng2-translate/commit/7bcd6f5fbd23f4718cc5ca365ae30fda94e22b67 (I don't know why github didn't close the PR)

**Comment by Dinistro** [comment]
@ocombe In my case, we only have dots and I think that my example

```
'key' : 'value',
'key.subkey' : 'another value'
```

is no redundancy. `key.subkey` exists and is not `undefinied`, so it should be translated.

I understand the convention problem of @ribizli and his solution, but this is not the same as my example.

**Comment by Dinistro** [comment]
@ocombe I created another Pull Request that solves my Issue.

**Pull request closed without merging**
