### PR TITLE
Handle the case where key or translation contains CR.

### PR DESCRIPTION
**Pull request by ksontini**
To avoid exception if the key or translation contain CR.

### CODE REVIEW

**Comment by ksontini** [comment]
When I try to run tests localy to fix my pull request, npm run test-watch failed to start.

Is there any special config, except npm install and run test?

**Comment by ocombe** [comment]
You need to have Firefox & Chrome installed and available in PATH. Do you get an error for the fail ?

**Comment by ksontini** [comment]
There are the errors in my console:

> ng2-translate@ test ...\ng2-translate
> tsc && karma start

node_modules/angular2/http/testing.d.ts(1,15): error TS2307: Cannot find module 'angular2/src/http/backends/mock_backend'.
src/translate.pipe.ts(1,91): error TS2307: Cannot find module 'angular2/core'.
src/translate.pipe.ts(3,34): error TS2307: Cannot find module 'angular2/src/facade/lang'.
src/translate.service.ts(1,50): error TS2307: Cannot find module 'angular2/core'.
src/translate.service.ts(2,30): error TS2307: Cannot find module 'angular2/http'.
ng2-translate.ts(1,23): error TS2307: Cannot find module 'angular2/core'.
ng2-translate.ts(2,20): error TS2307: Cannot find module 'angular2/http'.
tests/translate.pipe.spec.ts(2,43): error TS2307: Cannot find module 'angular2/src/http/backends/mock_backend'.

tests/translate.pipe.spec.ts(4,69): error TS2307: Cannot find module 'angular2/http'.
tests/translate.pipe.spec.ts(5,52): error TS2307: Cannot find module 'angular2/core'.
tests/translate.service.spec.ts(1,18): error TS2307: Cannot find module 'angular2/testing'.
tests/translate.service.spec.ts(2,33): error TS2307: Cannot find module 'angular2/core'.
tests/translate.service.spec.ts(3,69): error TS2307: Cannot find module 'angular2/http'.
tests/translate.service.spec.ts(4,9): error TS2305: Module '".../ng2-translate/node_modules/angular2/http/testing"' has no exported member 'MockBackend'.
tests/translate.service.spec.ts(4,22): error TS2305: Module '".../ng2-translate/node_modules/angular2/http/testing"' has no exported member 'MockConnection'.

**Comment by ocombe** [comment]
And you have Angular 2 installed in your node_modules folder ?

**Comment by ksontini** [comment]
The problem is in the npm install:

npm ERR! peerinvalid The package rxjs@5.0.0-beta.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.15 wants rxjs@5.0.0-beta.2

**Comment by ksontini** [comment]
@ocombe try a new clean install and test, it will fail.

This is related to the versions of devDependencies in the package.json

**Comment by ocombe** [comment]
Well the dev dependencies say: `"rxjs": "5.0.0-beta.2"`. I just tried a fresh install and I can run `npm test` with no problem, it installed beta 2 :-/

**Comment by ksontini** [comment]
Ok I'll check the version of rxjs later :)

For the pull request it self, it fix the my problem. If you find any regression, let me know to correct the patch.

**Comment by ksontini** [comment]
Well, This is stupid from my part. I'll close this PR as it's not a solution.

Assuming that a key containing a CR, is not a problem of ng2-translate.

The real problem is why CR in the string throw an Exception. A logic behavior is to call an errorHandler.

**Pull request closed without merging**
