### PR TITLE
configure of TranslateLoader and MissingTranslationHandler with angular2 DI only (#48)

### PR DESCRIPTION
**Pull request by ribizli**
Finally this PR has not much to do with #48, since Angular DI supports classes  and not interfaces.

Note! There are breaking changes in this PR.

### CODE REVIEW

**Comment by ocombe** [comment]
Wow this looks this really nice, thanks a lot !
I will take a closer look at this asap (but maybe not until this week end).

**Comment by ocombe** [comment]
I changed a few things, I renamed `NG_TRANSLATE_PROVIDERS` to `TRANSLATE_PROVIDERS` & I kept the methods `useLoader` & `setMissingTranslationHandler` because you might want to customize the service for one component only.

**Comment by ribizli** [comment]
You can (should!) also do that via DI. I'm against the setter version. But
you decide.

**Comment by ocombe** [comment]
Hmm how do you do that with DI in just one component?

**Comment by ribizli** [comment]
In providers of component you can use the same provide method like in
bootstrap.

**Comment by ocombe** [comment]
Oh nice, I didn't know that, I have to try :)
I'll remove the setters in the next version then.

**Pull request merged**
