### PR TITLE
chore(typings): best practices for new TS things

### PR DESCRIPTION
**Pull request by robwormald**
- removes / ignores generated code from repo, generated as a
pre-publish step.
- refactors index.ts to be slightly more idiomatic module style (meh)
- removes extraneous TSD things
- adds typings field to package.json

### CODE REVIEW

**Comment by ocombe** [comment]
Trying to concurrence @valorkin here ? :D
I'll check that out tonight if I have the time :)

**Comment by valorkin** [comment]
@ocombe  concurrence - no, help - yes
@robwormald really appreciate your help :)

**Comment by ocombe** [comment]
Ok that works ! Just added typescript as a dependency, and changed prepublish to postinstall script in npm package :)
I still get a warning in the typescript compiler, but it works nonetheless and I get correct auto completion with webstorm.
Kuddos guys, I think that we have a good dev process here.

**Comment by ocombe** [comment]
Had to adjust a few things with the new version of angular 2 alpha 42 that integrates typings, it works now (again).

**Comment by ocombe** [comment]
Or not.
This is driving me nuts :D

**Comment by valorkin** [comment]
set `prepublish` back, it works
it is something wrong with windows tsc or npm
and in general it works :)

**Comment by ocombe** [comment]
Yes, I did that. Rob explained to me how prepublish really works, the description on the npm website is just so confusing... :)

**Pull request merged**
