### PR TITLE
feat(MissingTranslationHandler): pass additional paramaters to `handle`

### LINKED ISSUE #160: Allow default translation without using MissingTranslationHandler
When a translation is missing it would be ideal if we could pass in a default fallback string to use if no translation is found (in current or default language). 

Suggested syntax:

``` html
{{'example.translation.key' | translate:{default:'Example Text'} }}
```

A specific use case for this is a dropdown list where the first few items (such as  item value=0 , text= [Unknown] are translated), but the other items are driven by an external data source and may or may not have a translation.

### PR DESCRIPTION
**Pull request by DethAriel**
* pass `key`, `translateService`, and `interpolateParams` (if provided) to the `handle` method of `MissingTranslationHandler` for advanced  scenarios.
* `MissingTranslationHandler` README adjustments based on new function interface

Obsoletes #214 .
Closes #160, #221

### CODE REVIEW

**Comment by ocombe** [comment]
Wow looks nice, you even added the tests ! Thanks, I'll try to take a look at it soon (but really busy until next week)

**Comment by ocombe** [comment]
Sorry, I didn't forget you, I just haven't had much time, I'll check this tomorrow

**Comment by c1rus** [comment]
new plans to merge this?

**Comment by DethAriel** [comment]
Fixed conflicts by rebasing onto the latest master, opened #275, closing current PR

**Pull request closed without merging**
